title: Autentimisteenus
baseurl: "https://e-gov.github.io/TARA-Doku"
viimatiMuudetud: "15.12.2017"

defaults:
  -
    scope:
      path: "" # Kõik failid
    values:
      layout: "Times"
      sidebar: "false"

  