title: Autentimisteenus
repo: "https://github.com/e-gov/TARA-Doku"
baseurl: "https://e-gov.github.io/TARA-Doku"

defaults:
  -
    scope:
      path: "" # Kõik failid
    values:
      layout: "Times"
      sidebar: "false"

  