title: Autentimisteenus
baseurl: "https://e-gov.github.io/TARA-Doku"
viimatiMuudetud: "02.01.2018"

defaults:
  -
    scope:
      path: "" # Kõik failid
    values:
      layout: "Times"
      sidebar: "false"

  